### ISSUE TITLE
Type CCT (WW/ CW)

### ISSUE THREAD

**Issue by Hanimaniac** [buenyamin-olgun/homebridge-milight-v6#3]
Hello,
first thanks for your Plugin for Homebridge. 
I use the milight fut035 for a warmwhite/ coldwhite led bulb. 
Is it possible to ad this „type“ of milight lamp to your Plugin?
So that in Homekit, there is a Lamp witch just change between warm and cold white?
Thanks 
Hanimaniac

**Comment by Zer0x00** [comment]
Hello,
thanks for your request.

Unfortunately the white bulbs are kinda working different in comparison with all other bulbs.

On all other bulbs you can send the command "set brightness to 80%", on the dualwhite bulbs you'll have to repeat the "brighter!" command until it reaches your defined value. This makes it difficult as I would have to set your value depending on the current value. Same for the temperature of the bulbs.

This is what I could understand from the source code of the node-milight-promise library which is used in this plugin.

Since I'm using the ESP8266 MiLight Hub and I don't own any FUT035 bulbs this is a difficult task to accomplish without doing any further testings.

Kind Regards
Büny

**Comment by Hanimaniac** [comment]
Hey Büny,
thanks for your fast answer. 
Ok. It just was a question. 
Its a pitty, so i hafe tu use the rgbww version. 

Thanks
Martin

**Comment by Zer0x00** [comment]
@Hanimaniac you could have a look at this plugin:
https://github.com/dotsam/homebridge-milight

**Comment by Hanimaniac** [comment]
@Zer0x00 
Thanks for your Answer,
I use a CCT Milight Controller for warm and cold white light.
Over the Milight app, i can control everything like a charm. 
But with the plugin, I can't control the light with homekit. 
I also have a 4 Zone LED Controller from Milight which works with the Plugin and Homekit.
